modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "GPL"

[[mods]]
modId = "tlt_tech"
version = "${mod_version}"
displayName = "TLT Tech"
authors = "fg"
description = '''TLT2 专用科技魔改模组'''

[[dependencies.tlt_tech]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.tlt_tech]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "AFTER"
side = "BOTH"

